In [2]:
#1. Stopwords: stop words are words which are filtered out before or after processing of natural

#Task 1 - Lexicons
#task 2 - collection of words/Phrases + Information (POS; tense Definitions..)
#Lexicon has lexical entries -> each entry is Word/Phrase -> has a HeadWord(Lemma) + Information


### Stop words are generally the most common words in a language.

In [3]:
#list of stopwords
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

## Getting CMU wordlist

In [4]:
#get list of CMU wordlist 
import nltk
entries=nltk.corpus.cmudict.entries()
len(entries)

133737

In [5]:
entries[:100]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N']),
 ("aaron's", ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aarons', ['EH1', 'R', 'AH0', 'N', 'Z']),
 ('aaronson', ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ('aaronson', ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N']),
 ("aaronson's", ['EH1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z']),
 ("aaronson's", ['AA1', 'R', 'AH0', 'N', 'S', 'AH0', 'N', 'Z'

In [6]:
#importing wordnet and getting sets
from nltk.corpus import wordnet as wn
wn.synsets('Vehicle')

[Synset('vehicle.n.01'),
 Synset('vehicle.n.02'),
 Synset('vehicle.n.03'),
 Synset('fomite.n.01')]

In [7]:
wn.synset('car.n.01').lemma_names()

['car', 'auto', 'automobile', 'machine', 'motorcar']

In [8]:
wn.synset('chair.n.01').lemma_names()

['chair']

In [9]:
wn.synset('gender.n.01').lemma_names()

['gender', 'grammatical_gender']

In [10]:
from nltk.corpus import wordnet as wn
wn.synsets('good')

[Synset('good.n.01'),
 Synset('good.n.02'),
 Synset('good.n.03'),
 Synset('commodity.n.01'),
 Synset('good.a.01'),
 Synset('full.s.06'),
 Synset('good.a.03'),
 Synset('estimable.s.02'),
 Synset('beneficial.s.01'),
 Synset('good.s.06'),
 Synset('good.s.07'),
 Synset('adept.s.01'),
 Synset('good.s.09'),
 Synset('dear.s.02'),
 Synset('dependable.s.04'),
 Synset('good.s.12'),
 Synset('good.s.13'),
 Synset('effective.s.04'),
 Synset('good.s.15'),
 Synset('good.s.16'),
 Synset('good.s.17'),
 Synset('good.s.18'),
 Synset('good.s.19'),
 Synset('good.s.20'),
 Synset('good.s.21'),
 Synset('well.r.01'),
 Synset('thoroughly.r.02')]

In [11]:
# Task 2 - Simple Text Classifier
def gender_features(word): #gives last letter of the word
    return {'last_letter':word[-1]}

In [12]:
#giving names
gender_features('Pratik')

{'last_letter': 'k'}

In [13]:
from nltk.corpus import names
labeled_names = ([(name, 'male') for name in names.words('male.txt')]+
[(name, 'female') for name in names.words('female.txt')])

In [14]:
import random
random.shuffle(labeled_names)

In [15]:
featuresets = [(gender_features(n),gender) for (n,gender) in labeled_names] #this is used to train the model
#this will have last letter of names followed by gender

In [16]:
featuresets

[({'last_letter': 'y'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'l'}, 'male'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 't'}, 'male'),
 ({'last_letter': 'e'}, 'male'),
 ({'last_letter': 'n'}, 'male'),
 ({'last_letter': 'r'}, 'female'),
 ({'last_letter': 'y'}, 'male'),
 ({'last_letter': 'n'}, 'female'),
 ({'last_letter': 'm'}, 'male'),
 ({'last_letter': 'l'}, 'female'),
 ({'last_letter': 'r'}, 'male'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'y'}, 'female'),
 ({'last_letter': 'y'}, 'male'),
 ({'last_letter': 'g'}, 'male'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'n'}, 'female'),
 ({'last_letter': 'l'}, 'male'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'i'}, 'female'),
 ({'last_letter': 'i'}, 'female'),
 ({'last_letter': 'a'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'last_letter': 'h'}, 'male'),
 ({'last_letter': 'y'}, 'female'),
 ({'last_letter': 'e'}, 'female'),
 ({'las

In [17]:
train_set,test_set=featuresets[500:],featuresets[:500]

In [23]:
import nltk
classifier = nltk.NaiveBayesClassifier.train(train_set)

In [24]:
import nltk
classifier2 =nltk.DecisionTreeClassifier.train(train_set)

In [25]:
classifier.classify(gender_features('Pratik'))

'male'

In [26]:
classifier2.classify(gender_features('Pratik'))

'male'

In [28]:
print(nltk.classify.accuracy(classifier, test_set))

0.784


In [29]:
print(nltk.classify.accuracy(classifier2, test_set))

0.784


## Task 3 - Vectorisers & cosine Similarity

In [19]:
#read more about countvectorizer
from sklearn.feature_extraction.text import CountVectorizer
#from sklearn.feature_extraction.text import TfidVectorizer

In [20]:
vect = CountVectorizer(binary = True)
corpus = ["Tessaract is good optical character recognition engine  ", "optical character recognition is significant "]
vect.fit(corpus) #it is the most imp step we need to fit the corpus to vectorizer

CountVectorizer(analyzer='word', binary=True, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
vocab=vect.vocabulary_ #built-in function where index for unique words in corpus

In [22]:
for key in sorted(vocab.keys()): #indexing of the words from corpus
     print("{}:{}".format(key, vocab[key]))

character:0
engine:1
good:2
is:3
optical:4
recognition:5
significant:6
tessaract:7


In [23]:
print(vect.transform(["This is a good optical illusion"]).toarray()) #tranform helps to do with any sentence other than in corpus
#we took one sentence and vectorized using vet vectorizer and got that 3 words are same

[[0 0 1 1 1 0 0 0]]


In [24]:
print(vect.transform(corpus).toarray())

[[1 1 1 1 1 1 0 1]
 [1 0 0 1 1 1 1 0]]


In [25]:
#cosine similartiy works, we can have different distance and similarity formula
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
print(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray())
print(vect.transform(["OCR is an optical character recognition engine"]).toarray())

[[1 1 0 1 0 1 0 0]]
[[1 1 0 1 1 1 0 0]]


In [27]:
similarity = cosine_similarity(vect.transform(["Google Cloud Vision is a character recognition engine"]).toarray(), vect.transform(["OCR is an optical character recognition engine"]).toarray()) #two different text given to vet and then cosine similarity 

In [28]:
print(similarity) #similarity between this two sentences

[[0.89442719]]


# Homework 
### Get two sentecnes-> exclude stop words-> form vectors-> compare them using cosine similarity

In [48]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
  
sentence2="Google Cloud Vision is a character recognition engine "
stop_words = set(stopwords.words('english')) 
word_tokens = word_tokenize(sentence2)
  
filtered_sentence2 = [w for w in word_tokens if not w in stop_words] 
print(filtered_sentence2)

['Google', 'Cloud', 'Vision', 'character', 'recognition', 'engine']


In [49]:
new=" ".join(filtered_sentence2)

In [50]:
new

'Google Cloud Vision character recognition engine'

In [51]:
vect.transform([new]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [55]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
  
sentence3="OCR is an optical character recognition engine "
stop_words = set(stopwords.words('english')) 
word_tokens = word_tokenize(sentence3)
  
filtered_sentence3 = [w for w in word_tokens if not w in stop_words] 
print(filtered_sentence3)

['OCR', 'optical', 'character', 'recognition', 'engine']


In [56]:
new2=" ".join(filtered_sentence3)

In [57]:
new2

'OCR optical character recognition engine'

In [58]:
vect.transform([new2]).toarray()

array([[1, 1, 0, 0, 1, 1, 0, 0]], dtype=int64)

In [59]:
similarity = cosine_similarity(vect.transform([new]).toarray(), vect.transform([new2]).toarray()) #two different text given to vet and then cosine similarity 

In [60]:
similarity

array([[0.8660254]])